name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.17.2
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies, --prod]
              cwd: web
      - run: npm run-script build
        working-directory: web
      - name: Copy files to the bucket with the AWS CLI
        run: aws --endpoint ${{ secrets.S3_ENDPOINT }} s3 sync web/build/ ${{ secrets.S3_WEB_BUCKET }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
